version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TaskManager
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Volume para persistir dados do PostgreSQL
    networks:
      - app-taskmanager-network

  java-app:
    build:
      context: .
    container_name: java-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/TaskManager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - app-taskmanager-network

volumes:
  postgres-data:  # Definindo o volume para persistir os dados do PostgreSQL
    driver: local  # Tipo de driver para o volume (local no caso, armazenado no host)

networks:
  app-taskmanager-network:
    driver: bridge
